debug: true
server:
  port: 8710
eureka:
  client:
    serviceUrl:
      #指向注册中心
      defaultZone: http://localhost:9001/eureka/
  instance:
    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1000000
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2000000
spring:
  application:
    name: gateway8710
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
logging:
  level:
    root: debug